config/routes.rb
Rails.application.routes.draw do
  # the following should go first, for helpers to pick it and not the api
  resources :ac_years

  scope path: ApplicationResource.endpoint_namespace, defaults: { format: :jsonapi } do
    resource :user_session, controller: 'user_session_api',
      only: %i[show create update destroy]
    resources :issues_issues_staffs, controller: 'api'
    resources :replaced_by_replaces, controller: 'api'
    resources :allows_requires, controller: 'api'
    resources :course_lists_courses, controller: 'api'
    resources :hosts_visitors, controller: 'api'
    resources :hosts_postdocs, controller: 'api'
    resources :students_supervisors, controller: 'api'
    resources :departments_generic_courses, controller: 'api'
    resources :course_lists_prog_prereqs, controller: 'api'
    resources :users_roles, controller: 'api'
    resources :members_research_groups, controller: 'api'
    resources :research_groups_seminars, controller: 'api'
    resources :seminars, controller: 'api'
    resources :basic_prog_prereqs, controller: 'api'
    resources :ac_years, controller: 'api'
    resources :course_lists, controller: 'api'
    resources :courses, controller: 'api'
    resources :degree_plans, controller: 'api'
    resources :degrees, controller: 'api'
    resources :events, controller: 'api'
    resources :free_plan_items, controller: 'api'
    resources :generic_courses, controller: 'api'
    resources :issues, controller: 'issues_api'
    resources :issue_responses, controller: 'issues_api'
    resources :issues_users, controller: 'issues_api'
    resources :issues_student_reps, controller: 'issues_api'
    resources :issues_aguda_reps, controller: 'issues_api'
    resources :issues_staffs, controller: 'api'
    resources :meetings, controller: 'api'
    resources :plan_items, controller: 'api'
    resources :prog_prereqs, controller: 'api'
    resources :precise_prog_prereqs, controller: 'api'
    resources :research_groups, controller: 'api'
    resources :research_groups_seminars, controller: 'api'
    resources :roles, controller: 'api'
    resources :shnatons, controller: 'api'
    resources :term_plans, controller: 'api'
    resources :terms, controller: 'terms_api'
    resources :users, controller: 'users_api'
    resources :academics, controller: 'api'
    resources :members, controller: 'api'
    resources :regulars, controller: 'api'
    resources :kameas, controller: 'api'
    resources :students, controller: 'api'
    resources :phds, controller: 'api'
    resources :mscs, controller: 'api'
    resources :postdocs, controller: 'api'
    resources :adjuncts, controller: 'api'
    resources :admins, controller: 'api'
    resources :externals, controller: 'api'
    resources :virtuals, controller: 'api'
    resources :visitors, controller: 'api'
    resources :departments, controller: 'api'
    resources :photos, controller: 'api'
    resources :settings, controller: 'api'
    resources :carousel_items, controller: 'api'
    resources :carousel_item_records, controller: 'api'
  end

  ### regular routes

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/  do

    #root to: 'pages#show', id: 'home', defaults: { format: 'html' }
    root to: 'ipages#home'
    resources :user_sessions, only: %i[create destroy]
    post 'login'   => 'user_sessions#create'
    get 'logout'  => 'user_sessions#destroy'
    delete 'logout'  => 'user_sessions#destroy'
    get 'layout' => 'pages#layout', id: 'layout'
    get 'carousel' => 'admin/carousel_items'

    # saml
    # we never use the saml_idp login form
    get '/saml/auth' => 'saml_idp#create'
    get '/saml/metadata' => 'saml_idp#show'
    post '/saml/auth' => 'saml_idp#create'
    match '/saml/logout' => 'saml_idp#logout', via: [:get, :post, :delete]

    # (semi-)static and inertia
    inertia 'people/positions' => 'People/Positions'

    inertia 'research/friedman' => 'research/friedman'
    get 'research/eckmann' => 'pages#show', id: 'eckmann'
    get 'research/center' => 'ipages#center'

    get 'teaching/grad' => 'pages#show', id: 'grad'

    inertia 'community/visitors' => 'community/visitors'
    get 'community/history' => 'pages#show', id: 'history'
    get 'community/school' => 'pages#show', id: 'school'

    inertia 'internal/resources' => 'StaticCards'
    inertia 'internal/support' => 'StaticCards'
    inertia 'internal/about' => 'Static'

    namespace :people do
      resources :members, :admins, :students, :postdocs, :adjuncts, :virtuals #, only: [:index, :new, :show]
      # aliases with additional helper methods.
      # XXX May want to reconsider this, as it sends /people/students to 
      # People::PhdsControllers, which does not exist
      resources :regulars, path: :members
      resources :kameas, path: :members
      #resources :phds#, path: :students
      #resources :mscs#, path: :students

      resources :users do
        collection do
          post 'delete'
          post 'upload'
          post 'generate_api_key'
        end
        member do
          post 'photo'
          patch 'photo'
          patch 'retire'
        end
      end

      resources :visitors, only: [:new, :edit, :create, :update, :destroy]
      get 'visitors' => 'postdocs#index'


    end

    namespace :research do
      # seminars and events now displayed
      get 'weekly', to: redirect('/')
      get 'faculty' => '/people/members#research'
      resources :research_groups do
        collection do
          get 'faculty'
        end
      end
      concern :seminar_c do
        resources :seminars do
          member do
            post 'create_ml'
          end
          resources :meetings, controller: 'seminar/meetings' do
            member do
              get 'email'
            end
          end
        end
      end
      concerns :seminar_c
      resources :terms, only: [], path: '' do
        concerns :seminar_c
      end
      resources :events do
        member do
          get 'email'
        end
      end
    end

    namespace :teaching do
      get 'hours' => '/people/users#hours'
      post 'hours' => '/people/users#reset_hours'
      #get 'undergrad', to: 
      #redirect('//in.bgu.ac.il/teva/math/Pages/ToarRishon.aspx')
      get 'catalog',
        to: redirect('https://bgu4u.bgu.ac.il/pls/scwp/!app.gate?app=ann')
      #to:redirect('//bgu4u.bgu.ac.il/pls/scwp/%21sc.AnnualSearchResults?on_course_department=201')
      resources :generic_courses
      resources :generic_courses, path: 'generic-courses'

      concern :course_c do
        resources :courses do
          collection do
            get 'gsheets_update'
          end
        end
      end
      concerns :course_c

      #resource :term, controller: 'terms', only: [:edit, :show, :update], 
      #  as: :cterm
      get '/cterm', to: redirect(path: '/teaching/courses')
      concern :shnaton_c do
        resource :shnaton, path: :handbook do
          resources :prog_prereqs
          resources :degrees, except: :index do
            collection do
              get  '', action: :show, controller: 'shnatons'
            end
            resources :plan_items, only: [:index, :destroy]
            resources :free_plan_items, only: [:index, :destroy]
            resources :prog_prereqs
            resources :degree_plans do
              resources :term_plans
            end
          end
          resources :course_lists
        end
      end
      concerns :shnaton_c
      resources :ac_years, only: [], path: '' do
        concerns :shnaton_c
      end

      resources :issues do
        collection do
          get 'login' => 'issues_user_sessions#new'
          post 'login'   => 'issues_user_sessions#create'
          get 'logout'  => 'issues_user_sessions#destroy'
          delete 'logout'  => 'issues_user_sessions#destroy'
        end
        member do
          post 'send_created'
          post 'send_update'
        end
      end
      resources :issue_responses, only: %i[create update destroy]
      resources :issues_users do
        member do
          delete 'reset_password'
        end
        collection do
          get 'gsheets_update'
        end
      end
      resources :departments

      # terms should be last
      resources :terms, path: '' do
        concerns :course_c
        member do
          get 'populate'
        end
      end

    end

    namespace :community do
      get 'map', 
        to: redirect('http://in.bgu.ac.il/maps/marcus_map.pdf', status: 302)
      get 'wiki', 
        to: redirect('//www.cs.bgu.ac.il/~wwwmath/postdoc/Main', status: 302)
      get 'school',
        to: redirect('https://sites.google.com/view/innaentova/math-for-highschoolers/%D7%9E%D7%93-%D7%9E%D7%AA%D7%9E%D7%98%D7%99%D7%A7%D7%94-%D7%91%D7%93%D7%A8%D7%95%D7%9D', status: 302)
      get 'imu', to: redirect('http://imu.org.il')
      get 'facebook', to: redirect('//www.facebook.com/math.bgu/')
    end

    namespace :internal do
      #get 'mattermost', to: redirect('http://se-web.cs.bgu.ac.il')
      get 'xmail', to: redirect('https://xmail.bgu.ac.il/')
    end

    namespace :admin do
      resource :app_setup, controller: :app_setup, only: [:edit, :show, :update]
      resources :roles
      resources :role_events
      resources :versions, only: [:index, :show, :destroy]
      resources :jobs, only: [:index, :destroy]
      resources :carousel_items
      get :mir, action: :index, controller: :mir
    end
  end

end

app/models/event.rb
# frozen_string_literal: true

class Event < BaseEvent
  resourcify
  include Durable
  attaches :descfiles
  extend FriendlyId
  friendly_id :to_slug

  after_create :create_carousel_item

  def to_slug
    title
  end

  # TODO: move this to settings
  @@old = 6.months.ago
  @@expires = 2.years

  scope :recent, ->(fr = @@old) {
    end_between(fr, Date.current.beginning_of_day)
  }
  scope :fresh, ->(today = Time.zone.today) {
    where('expires IS NULL OR expires > :today', today:)
  }
  scope :past, ->(til = @@old, today = Time.zone.today) {
    end_before(til).fresh(today)
  }

  scope :expired, ->(wh = Time.zone.today) {
    where('expires <= :when', when: wh)
  }

  scope :centre, -> { where(centre: true) }

  protected

  def carousel_opts
    super.merge(expires: ends)
  end

  def init
    super
    self.expires ||= Time.zone.today + @@expires if new_record?
    self.duration ||= Time.zone.now..Time.zone.now
  end
end

app/controllers/people/members/research_view.rb
# frozen_string_literal: true

class People::Members::ResearchView < BaseView
  def has_object?
    false
  end
end

app/controllers/research/events_controller.rb
# frozen_string_literal: true

class Research::EventsController < ApplicationController
  include Datewise

  helper_method :cur, :recent, :past
  objectify

  def email
    addr = current_user.decorate.email_address(true)
    Research::EventMailer.announce(object, addr).deliver_now
    safe_redir_back notice: "Email sent to '#{addr}'"
  end

  protected

  def cur
    @cur ||= expose_scope.end_from.asc.decorate
  end
  
  def recent
    @recent ||= expose_scope.recent.desc.decorate
  end
  
  def past
    @past ||= expose_scope.past.desc.decorate
  end

  def inertia_objects
    @inertia_objects ||= expose_scope.fresh.desc.decorate
  end

  def ical_title
    tt(:of_uni, what: tt('research.events'))
  end

  def serialize_objects
    [cur, recent, past].each do |l|
      l.map { |x| x.to_h(current_user) }
    end
  end

  def form_opts
    super.deep_merge(html: { multipart: true })
  end
end

app/controllers/research/research_groups/faculty_view.rb
# frozen_string_literal: true

class Research::ResearchGroups::FacultyView < BaseView
  def has_object?
    false
  end
end

app/controllers/research/research_groups_controller.rb
# frozen_string_literal: true

class Research::ResearchGroupsController < ApplicationController
  helper_method :tabs_to_name, :tabs_to_id, :groupless
  objectify

  def index
    # we may have a partial reload, so we don't load groups again, and don't 
    # run policy_scope
    skip_policy_scope
    inertia_index
  end

  def show
    redirect_to({action: :index, params: { research_group: object.to_param }})
    #inertia_show
  end

  protected

  def inertia_show_path
    inertia_index_path
  end

  def inertia_form_info
    super.vdeep_merge(
      seminars: inertia_form_fields(Seminar),
      members: inertia_form_fields(User.academic),
    )
  end

  def inertia_index_props
    res = super
    if params[:researchGroup]
      group = collection.find(params[:researchGroup]).try(:decorate)
      authorize group, :show?
      # preloading issues
      Regular # rubocop:disable Lint/Void
      Kamea # rubocop:disable Lint/Void
      if group
        res = res.vdeep_merge(
          researchGroup: -> { group.inertia_json },
        )
      end
    end
    res
  end

  def inertia_show_props
    super.vdeep_merge(inertia_index_props)
  end

  def groupless
    @groupless ||= policy_scope(Member.active.groupless).decorate
  end

  def tabs_to_name(obj = object)
    obj.to_s
  end

  def tabs_to_id(obj = object)
    obj.to_id
  end

  def ajax_prerender
    headers['X-tab-item'] = tabs_to_id
    headers['X-tab-name'] = tabs_to_name
  end
end

app/controllers/research/seminar/meetings_controller.rb
# frozen_string_literal: true

class Research::Seminar::MeetingsController < ApplicationController
  include Datewise
  helper_method :msg
  objectify

  def index
    respond_to do |format|
      format.any(:html, :tex, :pdf) do
        # We don't use policy_scope, since we redirect
        skip_policy_scope
        redirect_to seminar_any.decorate.show_path
      end
      format.any { super }
    end
  end

  def new
    super
    meeting.date = seminar.default_date
  end

  def email
    addr = current_user.decorate.email_address(true)
    Research::Seminar::MeetingMailer.announce(
      object, addr, subject: seminar.decorate.to_s
    ).deliver_now
    safe_redir_back notice: "Email sent to '#{addr}'"
  end

  def inertia_show_path
    'Research/Seminars/Meetings/Show'
  end

  def inertia_edit_path
    'Research/Seminars/Meetings/Edit'
  end

  protected

  def msg
    to = seminar.list_id || ''
    to += "@#{AppSetup.ml_mail_domain}" unless to.blank? || to.include?('@')

    @msg ||= Research::Seminar::MeetingMailer.announce(
      meeting, to, subject: seminar.decorate.to_s
    ).message
  end

  def term_id
    return @term_id if @term_id

    @term_id = params[:term] || params[:term_id]
    @term_id = 'fall2017' if @term_id.to_s == 'fall2018'
    @term_id
  end

  def seminar_id
    params[:seminar] || params[:seminar_id]
  end

  def term
    @term ||=
      begin
        Term.find(term_id)
      rescue ActiveRecord::RecordNotFound
        Term.current(perm_params(nil)[:date] || Date.current)
      end
  end

  def seminar
    @seminar ||= term&.seminars&.find(seminar_id)
  end

  def seminar_any
    seminar
  rescue ActiveRecord::RecordNotFound
    Seminar.find(seminar_id)
  end

  def title_opts
    sem = seminar_any.try(:decorate)
    super.merge(
      { seminar: sem }.merge(
        object ? { date: l(object.try(:date)) } : {},
      ),
    )
  end

  def collection
    policy_scope(seminar_any.meetings)
    #term_id ? seminar.meetings : Meeting.of_seminar(seminar_id)
  rescue ActiveRecord::RecordNotFound
    Meeting.none
  end

  # include all meetings of the seminar in the calendar, not just per term
  def ical_events
    policy_scope(Meeting.of_seminar(seminar_id))
  end

  def ical_title
    tt(:of_uni, what: seminar_any.decorate.to_s)
  end

  def ics_path(**)
    seminar.decorate.meetings_path(format: :ics, **)
  end

  def atom_author
    @atom_author ||= seminar_any.admin_users.first&.decorate
  end

  def atom_author_name
    atom_author&.to_s
  end

  def atom_author_email
    atom_author&.email_address
  end

  def atom_author_uri
    atom_author&.url
  end

  def massage_params
    super
    mparams = params[:meeting]
    return if mparams.blank?

    if mparams[:date].present?
      mparams[:date] = Date.strptime(mparams[:date], '%Y-%m-%d')
    end

    return unless mparams[:descfiles].respond_to?(:map)

    vf = mparams[:descfiles].reject { |d| d[:_destroy] }
    mparams[:descfiles] = vf.map { |d| d[:signed_id] || d }
    
  end

  def form_opts
    super.deep_merge(html: { multipart: true })
  end

  def form_resent
    super.merge(meeting_date: seminar.default_date)
  end
end

app/controllers/research/seminars/weekly_view.rb
# frozen_string_literal: true

class Research::Seminars::WeeklyView < BaseView
  def has_object?
    false
  end
end

app/views/research/events/_event.html.erb
<% cache object_cache_key(event) do %>
<li dir="auto">
  <p class="no-indent my-1">
    <%= event.action_list %>
    <%= event.online_icon %>
    <%= event.to_pagehtml('#centre') %>

  <%= render event.descfiles, size: :sm %>
  </p>

  <% if event.description %>
    <div class="seminar bordered mathjax mt-2 mb-3 px-1" dir="auto">
      <%= markdown(event.description) %>
    </div>
  <% end %>
</li>

<% end %>

app/views/research/events/_form.html.erb
<%= f.input :title %>
<hr/>
<%= f.input :web, as: :url %>
<%= f.input :description, pagedown %>
<%= f.input :descfiles, as: :attachment_preview, 
  label: tt('file', what: tt('description')) %>

<div class="row">
  <div class="col-md-6">
    <%= f.input :location %>
  </div>
  <div class="col-md-6">
    <%= f.input :online, input_html: { autocomplete: 'url' } %>
  </div>
</div>

<%= f.input :duration %>

<%= f.input :expires, as: :date_picker, html5: true %>

<%= f.input :slug %>

<%= f.input :centre, default: 1 %>

<%= f.input_admins %>

app/views/research/events/_index_center.he.html.erb
(<%= glyphicon(:star) %>) מסמל אירועים הנתמכים בחלקם על-ידי 
<a href="<%= research_center_path %>">המרכז ללימודים מתקדמים במתמטיקה</a> 
באוניברסיטת בן-גוריון

app/views/research/events/_index_center.html.erb
(<%= glyphicon(:star) %>) marks events partly supported by the 
<a href="<%= research_center_path %>">Center for Advanced Studies in 
  Mathematics</a> at Ben-Gurion University

app/views/research/events/_period.html.erb
<% unless list.empty? %>
  <div class="row-flex justify-content-center">
  <div class="col col-md-10 col-lg-8 my-2">
    <h3><%= title %></h3>
      <%= yield :top %>
       <ul class="event-list">
         <%= render list %>
       </ul>
  </div>
  </div>
 <% end %>

app/views/research/events/index.html.erb
<% content_for :head do %>
  <%= auto_discovery_link_tag :atom, research_events_url(format: :atom) %>
  <%= auto_discovery_link_tag :rss, research_events_url( format: :rss)%>
<% end %>

<%= h1 do %>
  <%= get_title %>
  <span class="formats">
    <%= link_to_glyphicon :ical, 
      research_events_url(format: :ics, protocol: 'webcal') %>
    <%= link_to_glyphicon :atom, research_events_url(format: :atom) %>
  </span>
<% end %>

<%= tabs([[tt('research.events!upcoming'), 'upcoming', cur],
          [tt('research.events!recent'), 'recent', recent],
          [tt('research.events!past'), 'past', past]].select{|x| 
            x.last.present? }) do |l| %>
<% if l[1] == 'past' %>
  <p class="text-larger text-center">
  <strong>Some older events may be found on the pages of the 
    <a href="<%= research_center_path(anchor: :past) %>">
      Center for Advanced Studies</a>.
  </strong>
  </p>
<% end %>

  <%= render partial: 'period', locals: { list: l[2], title: l[0] } %>
<% end %>

<div class="row-flex justify-content-center">
  <div class="bordered well col-md-6" id="centre">
    <%= render partial: 'index_center' %>
  </div>
</div>

<%= new_button %>

app/views/research/events/show.html.erb
<% provide(:title, event) %>
<%= h1 do %>
  <%= event %><%= event.action_list %>
<% end %>

<div class="row-flex justify-content-stretch align-items-center">
  <div class="col-auto">
    <dl class="row details-dl">
      <dt class="col-5"><%= tt 'coord.time' %></dt>
      <dd class="col-7"><%= date_range(event.starts, event.ends) %></dd>
      <dt class="col-5"><%= tt 'coord.place' %></dt>
      <dd class="col-7"><%= event.location %></dd>

<% unless current_page?(event.web) %>
      <dt class="col-5"><%= tt 'teaching.webpage' %></dt>
      <dd class="col-7"><%= event.linked %></dd>
<% end %>
    </dl>
  </div>
<% if event.online.present? %>
    <div class="col-auto">
      <%= event.online_btn %>
    </div>
  <% end %>
</div>


<% unless event.description.blank? and event.descfiles.empty? %>
  <div class="row-flex justify-content-center my-1">
<div class="col col-lg-10 col-xl-8 mathjax" dir="auto">
  <%= markdown(event.description) %>
  <%= embed event.descfiles %>
</div>
  </div>
<% end %>


    <div class="text-center my-1">
      <%= alt_fmt(:pdf) %>
      <%= alt_fmt(:tex) %>

      <% if current_user %>
        <%= footer_item(tt(:sendemail), email_research_event_path(event)) %>
      <% end %>

    </div>

app/views/research/events/show.pdf.erb
\begin{center}
\vspace*{\baselineskip}

{\Large <%= tt 'fdepname' %>}

\vspace*{\baselineskip}

\rule{\textwidth}{1.6pt}\vspace*{-\baselineskip}\vspace*{2pt}
\rule{\textwidth}{0.4pt}\\[\baselineskip]

{\Huge <%= lesc event %>}\\[0.2\baselineskip]

\rule{\textwidth}{0.4pt}\vspace*{-\baselineskip}\vspace{3.2pt}
\rule{\textwidth}{1.6pt}\\[\baselineskip]
\end{center}

<%= md2tex(event.description) %>

<%= embed event.descfiles %>

\vfill

\textbf{Time}: \emph{<%= date_range(event.starts, event.ends) %>}

\bigskip

\textbf{Location}: \emph{<%= lesc event.location %>}

\vspace*{2\baselineskip}

\bigskip

\textbf{Web}: \emph{<%= lesc event.web %>}


% vim: ft=eruby.tex:

app/views/research/events/show.tex.erb
./show.pdf.erb